version: "3"
services:
  server:
    build: .
    container_name: athletics-api
    ports:
      - "5000:5000"
    volumes:
      - ./src:/usr/src
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py